### ISSUE TITLE
Archivo token

### ISSUE THREAD

**Issue by emprenet** [bardcrack/JqueryUploadFilesWithBarProgress#1]
El archivo token.php tiene algunas instrucciones en especial que referencian a la función para generar los 20 caracteres?.
Al no estar entre los files descargables me confunde el contenido que pueda tener.
Gracias.
Jorge

**Comment by bardcrack** [comment]
Gracias por la observación, acabo de subir el archivo token.php, lo único que tiene ese archivo es una función con la cual podes crear token aleatorios del tamaño que necesites. Lo único que haces es pasar como argumento el tamaño del token que necesites.
